const actionTypes = {
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
  FETCH_HOME_LIST: 'FETCH_HOME_LIST',
  RECEIVE_HOME_LIST: 'RECEIVE_HOME_LIST',
  FETCH_HOME_LIST_ERR: 'FETCH_HOME_LIST_ERR'
}

export default actionTypes;